# Generated by Django 5.2.17 on 2026-09-27 13:36

import apps.judging.models
import core.clock
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0003_requiredartifact'),
        ('submissions', '0002_versions_immutable_once_submitted'),
        ('teams', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.CharField(default=apps.judging.models._assignment_id, editable=False, max_length=40, primary_key=True, serialize=False)),
                ('source', models.CharField(choices=[('batch', 'Assigned by an organizer'), ('auto', 'Assigned by the algorithm'), ('close_call', 'Extra review for a close call'), ('fixture', 'Imported')], max_length=12)),
                ('status', models.CharField(choices=[('proposed', 'Proposed'), ('active', 'Active'), ('done', 'Done'), ('withdrawn', 'Withdrawn')], default='active', max_length=10)),
                ('reason', models.CharField(blank=True, max_length=300)),
                ('queue_position', models.PositiveIntegerField(default=0, help_text='Randomised per judge so review order does not bias scores.')),
                ('created_by_id', models.CharField(blank=True, max_length=40)),
                ('created_at', models.DateTimeField(default=core.clock.now)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='events.event')),
                ('judge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='submissions.project')),
            ],
            options={
                'ordering': ['judge_id', 'queue_position'],
            },
        ),
        migrations.CreateModel(
            name='Conflict',
            fields=[
                ('id', models.CharField(default=apps.judging.models._conflict_id, editable=False, max_length=40, primary_key=True, serialize=False)),
                ('reason', models.CharField(blank=True, max_length=300)),
                ('declared_by_id', models.CharField(blank=True, max_length=40)),
                ('created_at', models.DateTimeField(default=core.clock.now)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conflicts', to='events.event')),
                ('judge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conflicts', to=settings.AUTH_USER_MODEL)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conflicts', to='teams.team')),
            ],
        ),
        migrations.CreateModel(
            name='JudgeTrack',
            fields=[
                ('id', models.CharField(default=apps.judging.models._judge_track_id, editable=False, max_length=40, primary_key=True, serialize=False)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='judge_tracks', to='events.event')),
                ('judge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='judge_tracks', to=settings.AUTH_USER_MODEL)),
                ('track', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='judges', to='events.track')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.CharField(default=apps.judging.models._review_id, editable=False, max_length=40, primary_key=True, serialize=False)),
                ('comment', models.TextField(blank=True)),
                ('improvement', models.TextField(blank=True, help_text='One thing the team should do next.')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted')], default='draft', max_length=10)),
                ('started_at', models.DateTimeField(default=core.clock.now)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('active_seconds', models.PositiveIntegerField(default=0)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='judging.assignment')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='events.event')),
                ('judge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='submissions.project')),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reviews', to='submissions.projectversion')),
            ],
            options={
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='ScoreItem',
            fields=[
                ('id', models.CharField(default=apps.judging.models._score_id, editable=False, max_length=40, primary_key=True, serialize=False)),
                ('value', models.SmallIntegerField()),
                ('criterion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='scores', to='events.criterion')),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='judging.review')),
            ],
        ),
        migrations.AddConstraint(
            model_name='assignment',
            constraint=models.UniqueConstraint(fields=('judge', 'project'), name='one_assignment_per_pair'),
        ),
        migrations.AddConstraint(
            model_name='conflict',
            constraint=models.UniqueConstraint(fields=('event', 'judge', 'team'), name='conflict_unique'),
        ),
        migrations.AddConstraint(
            model_name='judgetrack',
            constraint=models.UniqueConstraint(fields=('event', 'judge', 'track'), name='judge_track_unique'),
        ),
        migrations.AddConstraint(
            model_name='review',
            constraint=models.UniqueConstraint(fields=('assignment', 'version'), name='one_review_per_version'),
        ),
        migrations.AddConstraint(
            model_name='scoreitem',
            constraint=models.UniqueConstraint(fields=('review', 'criterion'), name='one_score_per_criterion'),
        ),
    ]
