# Generated by Django 5.2.17 on 2026-09-27 15:16

import apps.judging.models
import core.clock
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_requiredartifact'),
        ('judging', '0001_initial'),
        ('submissions', '0002_versions_immutable_once_submitted'),
    ]

    operations = [
        migrations.CreateModel(
            name='RankingDecision',
            fields=[
                ('id', models.CharField(default=apps.judging.models._decision_id, editable=False, max_length=40, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('confirm', 'Confirm the computed place'), ('place_above', 'Place directly above another project')], max_length=12)),
                ('rationale', models.TextField()),
                ('actor_id', models.CharField(blank=True, max_length=40)),
                ('created_at', models.DateTimeField(default=core.clock.now)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ranking_decisions', to='events.event')),
                ('other', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='submissions.project')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='submissions.project')),
            ],
            options={
                'ordering': ['created_at', 'id'],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('kind', 'confirm'), ('other__isnull', True)), models.Q(('kind', 'place_above'), ('other__isnull', False)), _connector='OR'), name='decision_other_matches_kind'), models.CheckConstraint(condition=models.Q(('rationale', ''), _negated=True), name='decision_needs_rationale')],
            },
        ),
    ]
