# Generated by Django 5.2.17 on 2026-09-27 15:28

import core.clock
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_requiredartifact'),
        ('judging', '0005_results_snapshots_append_only'),
    ]

    operations = [
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='publication', serialize=False, to='events.event')),
                ('published_by_id', models.CharField(blank=True, max_length=40)),
                ('published_at', models.DateTimeField(default=core.clock.now)),
                ('snapshot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='judging.resultssnapshot')),
            ],
        ),
    ]
