# Generated by Django 5.2.17 on 2026-09-27 15:42

import apps.judging.models
import core.clock
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_requiredartifact'),
        ('judging', '0008_result_query'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScoreEvent',
            fields=[
                ('id', models.CharField(default=apps.judging.models._score_event_id, editable=False, max_length=40, primary_key=True, serialize=False)),
                ('seq', models.PositiveIntegerField()),
                ('review_id', models.CharField(db_index=True, max_length=40)),
                ('payload', models.JSONField()),
                ('payload_hash', models.CharField(max_length=64)),
                ('prev_hash', models.CharField(max_length=64)),
                ('entry_hash', models.CharField(max_length=64)),
                ('signature', models.CharField(max_length=128)),
                ('key_id', models.CharField(max_length=16)),
                ('created_at', models.DateTimeField(default=core.clock.now)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ledger', to='events.event')),
            ],
            options={
                'ordering': ['event_id', 'seq'],
                'constraints': [models.UniqueConstraint(fields=('event', 'seq'), name='ledger_seq_per_event')],
            },
        ),
    ]
