# Generated by Django 5.2.17 on 2026-09-27 15:52

import apps.judging.models
import core.clock
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_requiredartifact'),
        ('judging', '0011_backfill_score_ledger'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Credential',
            fields=[
                ('id', models.CharField(default=apps.judging.models._credential_id, editable=False, max_length=40, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('protocol', 'Judge protocol'), ('certificate', 'Judging certificate'), ('participation', 'Participation record')], max_length=15)),
                ('number', models.PositiveIntegerField()),
                ('code', models.CharField(max_length=24, unique=True)),
                ('payload', models.JSONField()),
                ('payload_hash', models.CharField(max_length=64)),
                ('signature', models.CharField(max_length=128)),
                ('key_id', models.CharField(max_length=16)),
                ('public_key', models.CharField(max_length=64)),
                ('issued_at', models.DateTimeField(default=core.clock.now)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credentials', to='events.event')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credentials', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['kind', 'number'],
                'constraints': [models.UniqueConstraint(fields=('kind', 'number'), name='credential_number_per_kind'), models.UniqueConstraint(fields=('kind', 'event', 'user'), name='one_credential_per_kind_event_user')],
            },
        ),
    ]
