# Generated by Django 5.2.17 on 2026-09-27 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judging', '0013_credentials_append_only'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='source',
            field=models.CharField(choices=[('batch', 'Assigned by an organizer'), ('auto', 'Assigned by the algorithm'), ('close_call', 'Extra review for a close call'), ('fixture', 'Imported'), ('import', 'Imported from an event bundle')], max_length=12),
        ),
    ]
