# Generated by Django 5.2.17 on 2026-09-28 15:51

import apps.judging.models
import core.clock
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_alter_event_voting_mode'),
        ('judging', '0014_alter_assignment_source'),
        ('submissions', '0003_alter_projectversion_source'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PairwiseComparison',
            fields=[
                ('id', models.CharField(default=apps.judging.models._comparison_id, editable=False, max_length=40, primary_key=True, serialize=False)),
                ('outcome', models.CharField(choices=[('a', 'The first project is stronger'), ('b', 'The second project is stronger'), ('tie', 'Too close to call')], max_length=3)),
                ('created_at', models.DateTimeField(default=core.clock.now)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comparisons', to='events.event')),
                ('judge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comparisons', to=settings.AUTH_USER_MODEL)),
                ('project_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='submissions.project')),
                ('project_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='submissions.project')),
            ],
            options={
                'ordering': ['created_at', 'id'],
                'constraints': [models.UniqueConstraint(fields=('judge', 'project_a', 'project_b'), name='one_comparison_per_pair'), models.CheckConstraint(condition=models.Q(('project_a__lt', models.F('project_b'))), name='comparison_pair_ordered')],
            },
        ),
    ]
