# Generated by Django 5.2.17 on 2026-09-27 11:30

import apps.events.models
import core.clock
import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.CharField(default=apps.events.models._event_id, editable=False, max_length=40, primary_key=True, serialize=False)),
                ('slug', models.SlugField(max_length=80, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('phase', models.CharField(choices=[('draft', 'Draft'), ('registration', 'Registration'), ('submissions', 'Submissions open'), ('eligibility', 'Eligibility review'), ('judging', 'Judging'), ('deliberation', 'Deliberation'), ('published', 'Results published'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('template_key', models.CharField(blank=True, max_length=60)),
                ('registration_opens_at', models.DateTimeField(blank=True, null=True)),
                ('registration_closes_at', models.DateTimeField(blank=True, null=True)),
                ('submissions_open_at', models.DateTimeField(blank=True, null=True)),
                ('submissions_close_at', models.DateTimeField(blank=True, null=True)),
                ('judging_closes_at', models.DateTimeField(blank=True, null=True)),
                ('results_published_at', models.DateTimeField(blank=True, null=True)),
                ('weighting', models.CharField(choices=[('percent', 'Percent weights (sum to 100)'), ('multiplier', 'Relative multipliers')], default='percent', max_length=12)),
                ('reviews_per_project', models.PositiveSmallIntegerField(default=3)),
                ('max_load_per_judge', models.PositiveSmallIntegerField(default=12)),
                ('blind_judging', models.BooleanField(default=False)),
                ('max_team_size', models.PositiveSmallIntegerField(default=4)),
                ('allow_multiple_projects', models.BooleanField(default=False)),
                ('voting_mode', models.CharField(choices=[('off', 'No public vote'), ('link', 'Link-based ballot tokens'), ('email', 'Email-verified voters'), ('auth', 'Signed-in participants')], default='off', max_length=10)),
                ('voting_scheme', models.CharField(choices=[('single', 'One vote per voter'), ('quadratic', 'Quadratic (credits)')], default='single', max_length=10)),
                ('qv_credits', models.PositiveSmallIntegerField(default=9)),
                ('voting_opens_at', models.DateTimeField(blank=True, null=True)),
                ('voting_closes_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=core.clock.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.CheckConstraint(condition=models.Q(('submissions_open_at__isnull', True), ('submissions_close_at__isnull', True), ('submissions_open_at__lt', models.F('submissions_close_at')), _connector='OR'), name='event_submission_window_ordered'), models.CheckConstraint(condition=models.Q(('voting_opens_at__isnull', True), ('voting_closes_at__isnull', True), ('voting_opens_at__lt', models.F('voting_closes_at')), _connector='OR'), name='event_voting_window_ordered'), models.CheckConstraint(condition=models.Q(('reviews_per_project__gte', 1)), name='event_reviews_per_project_positive')],
            },
        ),
        migrations.CreateModel(
            name='CustomQuestion',
            fields=[
                ('id', models.CharField(default=apps.events.models._question_id, editable=False, max_length=40, primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=200)),
                ('help_text', models.CharField(blank=True, max_length=300)),
                ('kind', models.CharField(choices=[('text', 'Short text'), ('long_text', 'Long text'), ('url', 'Link'), ('choice', 'Choice'), ('bool', 'Yes / no')], default='text', max_length=12)),
                ('choices', models.JSONField(blank=True, default=list)),
                ('required', models.BooleanField(default=False)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='events.event')),
            ],
            options={
                'ordering': ['order', 'label'],
            },
        ),
        migrations.CreateModel(
            name='PhaseTransition',
            fields=[
                ('id', models.CharField(default=apps.events.models._transition_id, editable=False, max_length=40, primary_key=True, serialize=False)),
                ('from_phase', models.CharField(choices=[('draft', 'Draft'), ('registration', 'Registration'), ('submissions', 'Submissions open'), ('eligibility', 'Eligibility review'), ('judging', 'Judging'), ('deliberation', 'Deliberation'), ('published', 'Results published'), ('archived', 'Archived')], max_length=20)),
                ('to_phase', models.CharField(choices=[('draft', 'Draft'), ('registration', 'Registration'), ('submissions', 'Submissions open'), ('eligibility', 'Eligibility review'), ('judging', 'Judging'), ('deliberation', 'Deliberation'), ('published', 'Results published'), ('archived', 'Archived')], max_length=20)),
                ('actor_id', models.CharField(blank=True, max_length=40)),
                ('reason', models.TextField(blank=True)),
                ('overridden', models.BooleanField(default=False)),
                ('preflight', models.JSONField(blank=True, default=list)),
                ('at', models.DateTimeField(default=core.clock.now)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transitions', to='events.event')),
            ],
            options={
                'ordering': ['-at'],
            },
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.CharField(default=apps.events.models._track_id, editable=False, max_length=40, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracks', to='events.event')),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Prize',
            fields=[
                ('id', models.CharField(default=apps.events.models._prize_id, editable=False, max_length=40, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('rank', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('amount', models.CharField(blank=True, max_length=60)),
                ('description', models.TextField(blank=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prizes', to='events.event')),
                ('track', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='events.track')),
            ],
            options={
                'ordering': ['rank', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Criterion',
            fields=[
                ('id', models.CharField(default=apps.events.models._criterion_id, editable=False, max_length=40, primary_key=True, serialize=False)),
                ('key', models.SlugField(max_length=60)),
                ('label', models.CharField(max_length=160)),
                ('description', models.TextField(blank=True)),
                ('weight', models.DecimalField(decimal_places=3, default=Decimal('1'), max_digits=7)),
                ('min_score', models.SmallIntegerField(default=1)),
                ('max_score', models.SmallIntegerField(default=5)),
                ('anchors', models.JSONField(blank=True, default=dict)),
                ('is_gate', models.BooleanField(default=False)),
                ('gate_threshold', models.DecimalField(blank=True, decimal_places=3, max_digits=7, null=True)),
                ('is_bonus', models.BooleanField(default=False)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='criteria', to='events.event')),
            ],
            options={
                'ordering': ['order', 'key'],
                'constraints': [models.UniqueConstraint(fields=('event', 'key'), name='criterion_key_unique_per_event'), models.CheckConstraint(condition=models.Q(('min_score__lt', models.F('max_score'))), name='criterion_range'), models.CheckConstraint(condition=models.Q(('weight__gte', 0)), name='criterion_weight_non_negative'), models.CheckConstraint(condition=models.Q(('is_gate', False), ('gate_threshold__isnull', False), _connector='OR'), name='criterion_gate_has_threshold')],
            },
        ),
        migrations.AddConstraint(
            model_name='track',
            constraint=models.UniqueConstraint(fields=('event', 'name'), name='track_name_unique_per_event'),
        ),
        migrations.AddConstraint(
            model_name='prize',
            constraint=models.CheckConstraint(condition=models.Q(('rank__gte', 1)), name='prize_rank_positive'),
        ),
    ]
