# Generated by Django 5.2.17 on 2026-09-27 13:30

import apps.events.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_phase_history_append_only'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequiredArtifact',
            fields=[
                ('id', models.CharField(default=apps.events.models._artifact_id, editable=False, max_length=40, primary_key=True, serialize=False)),
                ('key', models.SlugField(max_length=60)),
                ('label', models.CharField(max_length=160)),
                ('kind', models.CharField(choices=[('file', 'File upload'), ('url', 'Link'), ('text', 'Text')], default='file', max_length=10)),
                ('parser', models.CharField(blank=True, max_length=60)),
                ('required', models.BooleanField(default=True)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='required_artifacts', to='events.event')),
            ],
            options={
                'ordering': ['order', 'key'],
                'constraints': [models.UniqueConstraint(fields=('event', 'key'), name='artifact_key_unique_per_event')],
            },
        ),
    ]
