# Generated by Django 5.2.17 on 2026-09-27 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_requiredartifact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='voting_mode',
            field=models.CharField(choices=[('off', 'No public vote'), ('link', 'Link-based ballot tokens'), ('email', 'Email-verified voters'), ('auth', 'Signed-in participants'), ('all', 'All of these: links, email and signed-in accounts')], default='off', max_length=10),
        ),
    ]
