# Generated by Django 5.2.17 on 2026-09-29 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_alter_event_voting_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='vote_burst_limit',
            field=models.PositiveSmallIntegerField(default=10, help_text='Votes from one network per minute before more are held for review.'),
        ),
        migrations.AddField(
            model_name='event',
            name='vote_email_domains',
            field=models.JSONField(blank=True, default=list, help_text='If set, email voting links only for these domains.'),
        ),
        migrations.AddField(
            model_name='event',
            name='vote_trusted_networks',
            field=models.JSONField(blank=True, default=list, help_text="CIDR ranges (the venue's network) never held as a burst."),
        ),
    ]
