# Generated by Django 5.2.17 on 2026-09-27 11:30

import apps.accounts.models
import core.clock
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_magic_links_and_judge_profiles'),
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoleGrant',
            fields=[
                ('id', models.CharField(default=apps.accounts.models._grant_id, editable=False, max_length=40, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('participant', 'Participant'), ('judge', 'Judge'), ('organizer', 'Organizer')], max_length=20)),
                ('created_at', models.DateTimeField(default=core.clock.now)),
                ('created_by_id', models.CharField(blank=True, max_length=40)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grants', to='events.event')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grants', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['event_id', 'role', 'user_id'],
                'constraints': [models.UniqueConstraint(fields=('user', 'event', 'role'), name='grant_unique')],
            },
        ),
    ]
