# Generated by Django 5.2.17 on 2026-09-27 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_rolegrant'),
    ]

    operations = [
        migrations.AddField(
            model_name='judgeprofile',
            name='public_passport',
            field=models.BooleanField(default=False, help_text="Show this judge's certificates on a public passport page (opt-in)."),
        ),
    ]
