# Generated by Django 5.2.17 on 2026-09-27 10:27

import core.clock
import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.CharField(default=core.models._audit_id, editable=False, max_length=40, primary_key=True, serialize=False)),
                ('at', models.DateTimeField(db_index=True, default=core.clock.now)),
                ('actor_id', models.CharField(blank=True, db_index=True, max_length=40)),
                ('actor_role', models.CharField(blank=True, max_length=20)),
                ('event_id', models.CharField(blank=True, db_index=True, max_length=40)),
                ('action', models.CharField(db_index=True, max_length=80)),
                ('target_type', models.CharField(blank=True, max_length=40)),
                ('target_id', models.CharField(blank=True, db_index=True, max_length=40)),
                ('summary', models.CharField(max_length=300)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('ip_hash', models.CharField(blank=True, max_length=64)),
            ],
            options={
                'ordering': ['-at', '-id'],
            },
        ),
    ]
