# Generated by Django 5.2.17 on 2026-09-27 10:37

import core.clock
import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_audit_append_only'),
    ]

    operations = [
        migrations.CreateModel(
            name='OutboxMessage',
            fields=[
                ('id', models.CharField(default=core.models._outbox_id, editable=False, max_length=40, primary_key=True, serialize=False)),
                ('kind', models.CharField(db_index=True, max_length=40)),
                ('payload', models.JSONField(default=dict)),
                ('dedupe_key', models.CharField(blank=True, max_length=200, null=True, unique=True)),
                ('created_at', models.DateTimeField(default=core.clock.now)),
                ('next_attempt_at', models.DateTimeField(db_index=True, default=core.clock.now)),
                ('claimed_until', models.DateTimeField(blank=True, null=True)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('done_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('failed_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
