# Generated by Django 5.2.17 on 2026-09-27 13:30

import apps.submissions.models
import core.clock
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0003_requiredartifact'),
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.CharField(default=apps.submissions.models._project_id, editable=False, max_length=40, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('withdrawn', 'Withdrawn'), ('disqualified', 'Disqualified')], default='draft', max_length=15)),
                ('gallery_order', models.PositiveIntegerField(default=0)),
                ('eligibility', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(default=core.clock.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='events.event')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='teams.team')),
                ('track', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='events.track')),
            ],
            options={
                'ordering': ['gallery_order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectVersion',
            fields=[
                ('id', models.CharField(default=apps.submissions.models._version_id, editable=False, max_length=40, primary_key=True, serialize=False)),
                ('n', models.PositiveIntegerField()),
                ('name', models.CharField(max_length=200)),
                ('tagline', models.CharField(blank=True, max_length=300)),
                ('description', models.TextField(blank=True)),
                ('thumbnail', models.FileField(blank=True, upload_to='thumbnails/')),
                ('video_url', models.URLField(blank=True, max_length=500)),
                ('repo_url', models.URLField(blank=True, max_length=500)),
                ('live_url', models.URLField(blank=True, max_length=500)),
                ('tech_tags', models.JSONField(blank=True, default=list)),
                ('source', models.CharField(choices=[('ui', 'Submission form'), ('api', 'REST API'), ('fixture', 'Fixture import'), ('import', 'Bulk import')], default='ui', max_length=10)),
                ('source_ref', models.CharField(blank=True, max_length=60)),
                ('created_at', models.DateTimeField(default=core.clock.now)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='submissions.project')),
            ],
            options={
                'ordering': ['project_id', 'n'],
            },
        ),
        migrations.CreateModel(
            name='ProjectImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='images/')),
                ('alt', models.CharField(blank=True, max_length=200)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='submissions.projectversion')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='project',
            name='canonical_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='submissions.projectversion'),
        ),
        migrations.CreateModel(
            name='CustomAnswer',
            fields=[
                ('id', models.CharField(default=apps.submissions.models._answer_id, editable=False, max_length=40, primary_key=True, serialize=False)),
                ('value', models.TextField(blank=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='events.customquestion')),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='submissions.projectversion')),
            ],
        ),
        migrations.CreateModel(
            name='ArtifactUpload',
            fields=[
                ('id', models.CharField(default=apps.submissions.models._upload_id, editable=False, max_length=40, primary_key=True, serialize=False)),
                ('file', models.FileField(blank=True, upload_to='artifacts/')),
                ('url', models.URLField(blank=True, max_length=500)),
                ('text', models.TextField(blank=True)),
                ('parsed', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(default=core.clock.now)),
                ('artifact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploads', to='events.requiredartifact')),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artifacts', to='submissions.projectversion')),
            ],
        ),
        migrations.AddConstraint(
            model_name='projectversion',
            constraint=models.UniqueConstraint(fields=('project', 'n'), name='version_number_unique'),
        ),
        migrations.AddConstraint(
            model_name='projectversion',
            constraint=models.CheckConstraint(condition=models.Q(('n__gte', 1)), name='version_number_positive'),
        ),
        migrations.AddConstraint(
            model_name='customanswer',
            constraint=models.UniqueConstraint(fields=('version', 'question'), name='one_answer_per_question'),
        ),
        migrations.AddConstraint(
            model_name='artifactupload',
            constraint=models.UniqueConstraint(fields=('version', 'artifact'), name='one_upload_per_artifact'),
        ),
    ]
