# Generated by Django 5.2.17 on 2026-09-27 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0002_versions_immutable_once_submitted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectversion',
            name='source',
            field=models.CharField(choices=[('ui', 'Submission form'), ('api', 'REST API'), ('fixture', 'Fixture import'), ('import', 'Bulk import'), ('demo', 'Demo data')], default='ui', max_length=10),
        ),
    ]
