"""Generate the README's acceptance truth table from the checker reports.

The table is never edited by hand: this script reads the claim in
.dogfood.toml, the official report (acceptance-report.txt) and, when present,
the extended report (acceptance-extended-report.txt), and rewrites the block
between the truth-table markers in README.md. It also records the SHA-256 of
the official checker and fixtures, so anyone can see they are unmodified.

    python3 tools/truth_table.py           # rewrite README.md
    python3 tools/truth_table.py --check   # exit 1 if README.md is out of date

Standard library only.
"""

import argparse
import hashlib
import re
import sys
import tomllib
from dataclasses import dataclass
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
BEGIN = "<!-- truth-table:begin (generated by tools/truth_table.py; do not edit by hand) -->"
END = "<!-- truth-table:end -->"

TIERS = {"T1": "Core", "T2": "Judging", "T3": "Public", "T4": "Stretch"}
# Published by the organizers (https://dogfoodhack.com/spec/).
OFFICIAL_FILES = {
    "tools/run.py": "aa98963841bc8e18e8e5d76f0499697c093dd3c0055f9d73a459f592f4dcf09d",
    "data/fixtures.json": "252896bc45d49fca69ad413be40c6bfde9d9b9f9dd8db702b3ff74eaaa181121",
}
REPORTS = {
    "official": "acceptance-report.txt",
    "extended": "acceptance-extended-report.txt",
}
_CHECK = re.compile(r"^(T\d)\s+(.+?)\s+\.+\s+(PASS|FAIL|SKIP)\b")
_CLAIM = re.compile(r"^claimed\s.*,\s*verified\b.*$")


@dataclass(frozen=True)
class Check:
    tier: str
    name: str
    result: str
    report: str


def parse_report(text: str, report: str) -> tuple[list[Check], str]:
    checks, claim_line = [], ""
    for line in text.splitlines():
        match = _CHECK.match(line.strip())
        if match:
            checks.append(Check(match[1], match[2], match[3], report))
        elif _CLAIM.match(line.strip()):
            claim_line = line.strip()
    return checks, claim_line


def _count(checks: list[Check], tier: str) -> str:
    mine = [c for c in checks if c.tier == tier]
    if not mine:
        return "none"
    passed = sum(c.result == "PASS" for c in mine)
    return f"{passed}/{len(mine)} pass"


def status(tier: str, claimed: set[str], checks: list[Check]) -> str:
    mine = [c for c in checks if c.tier == tier]
    failing = [c for c in mine if c.result != "PASS"]
    if tier in claimed:
        if not mine:
            return "**claimed, not yet checked**"
        return "**claimed, FAILING**" if failing else "**verified**"
    passing = [c for c in mine if c.result == "PASS"]
    if passing:
        return f"started, not claimed ({len(passing)}/{len(mine)} checks pass)"
    return "not claimed"


def _sha256(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def render(root: Path = ROOT) -> str:
    config = tomllib.loads((root / ".dogfood.toml").read_text(encoding="utf-8"))
    claimed = set(config.get("tiers", {}).get("claimed", []))
    checks: list[Check] = []
    claim_line = ""
    present = []
    for report, filename in REPORTS.items():
        path = root / filename
        if path.is_file():
            found, line = parse_report(path.read_text(encoding="utf-8"), report)
            checks += found
            present.append(f"[`{filename}`]({filename})")
            if report == "official":
                claim_line = line

    out = [BEGIN, ""]
    out.append(f"`{claim_line or 'no official report yet'}`, from {' and '.join(present)}.")
    out += ["", "| Tier | Claimed | Official checks | Extended checks | Status |"]
    out.append("|---|---|---|---|---|")
    official = [c for c in checks if c.report == "official"]
    extended = [c for c in checks if c.report == "extended"]
    for tier, label in TIERS.items():
        out.append(
            f"| {tier} {label} | {'yes' if tier in claimed else 'no'} | "
            f"{_count(official, tier)} | {_count(extended, tier)} | "
            f"{status(tier, claimed, checks)} |"
        )
    out += ["", "| Check | Report | Result |", "|---|---|---|"]
    out += [f"| {c.tier} {c.name} | {c.report} | {c.result} |" for c in checks]
    out += ["", "| Official file | SHA-256 | |", "|---|---|---|"]
    for name, expected in OFFICIAL_FILES.items():
        path = root / name
        actual = _sha256(path) if path.is_file() else "missing"
        verdict = "unmodified" if actual == expected else "**DIFFERS from the published file**"
        out.append(f"| `{name}` | `{actual}` | {verdict} |")
    out += ["", END]
    return "\n".join(out)


def apply(readme: str, block: str) -> str:
    start, end = readme.find(BEGIN), readme.find(END)
    if start == -1 or end == -1 or end < start:
        raise SystemExit("README.md has no truth-table markers")
    return readme[:start] + block + readme[end + len(END) :]


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--check", action="store_true", help="Exit 1 if README.md is stale.")
    args = parser.parse_args(argv)
    readme_path = ROOT / "README.md"
    readme = readme_path.read_text(encoding="utf-8")
    updated = apply(readme, render())
    if args.check:
        if updated != readme:
            print("README.md truth table is out of date: run python3 tools/truth_table.py")
            return 1
        print("README.md truth table is up to date")
        return 0
    readme_path.write_text(updated, encoding="utf-8", newline="\n")
    print("README.md truth table regenerated")
    return 0


if __name__ == "__main__":
    sys.exit(main())
