# Generated by Django 5.2.17 on 2026-09-27 16:25

import apps.voting.models
import core.clock
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0004_alter_event_voting_mode'),
        ('submissions', '0002_versions_immutable_once_submitted'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BallotToken',
            fields=[
                ('id', models.CharField(default=apps.voting.models._token_id, editable=False, max_length=40, primary_key=True, serialize=False)),
                ('channel', models.CharField(choices=[('link', 'Link minted by an organizer'), ('email', 'Link sent to a verified email'), ('member', 'Signed-in account')], max_length=10)),
                ('token_hash', models.CharField(max_length=64, unique=True)),
                ('email_key', models.CharField(blank=True, db_index=True, max_length=64)),
                ('seed', models.PositiveBigIntegerField()),
                ('credits', models.PositiveSmallIntegerField(default=1)),
                ('created_by_id', models.CharField(blank=True, max_length=40)),
                ('created_at', models.DateTimeField(default=core.clock.now)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ballots', to='events.event')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ballots', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.CharField(default=apps.voting.models._comment_id, editable=False, max_length=40, primary_key=True, serialize=False)),
                ('body', models.TextField(max_length=2000)),
                ('created_at', models.DateTimeField(default=core.clock.now)),
                ('hidden_at', models.DateTimeField(blank=True, null=True)),
                ('hidden_by_id', models.CharField(blank=True, max_length=40)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='submissions.project')),
            ],
            options={
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.CharField(default=apps.voting.models._vote_id, editable=False, max_length=40, primary_key=True, serialize=False)),
                ('credits', models.PositiveSmallIntegerField(default=1)),
                ('status', models.CharField(choices=[('counted', 'Counted'), ('quarantined', 'Held for review'), ('rejected', 'Rejected after review')], default='counted', max_length=12)),
                ('ip_hash', models.CharField(blank=True, db_index=True, max_length=32)),
                ('created_at', models.DateTimeField(db_index=True, default=core.clock.now)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='events.event')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='submissions.project')),
                ('token', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='voting.ballottoken')),
            ],
        ),
        migrations.AddConstraint(
            model_name='ballottoken',
            constraint=models.UniqueConstraint(condition=models.Q(('channel', 'member')), fields=('event', 'user'), name='one_member_ballot_per_event'),
        ),
        migrations.AddConstraint(
            model_name='ballottoken',
            constraint=models.UniqueConstraint(condition=models.Q(('email_key', ''), _negated=True), fields=('event', 'email_key'), name='one_email_ballot_per_event'),
        ),
        migrations.AddConstraint(
            model_name='vote',
            constraint=models.UniqueConstraint(fields=('token', 'project'), name='one_vote_per_ballot_project'),
        ),
    ]
