# Generated by Django 5.2.17 on 2026-09-27 16:38

import apps.integrations.models
import core.clock
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0004_alter_event_voting_mode'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Webhook',
            fields=[
                ('id', models.CharField(default=apps.integrations.models._webhook_id, editable=False, max_length=40, primary_key=True, serialize=False)),
                ('url', models.URLField(max_length=500)),
                ('events', models.JSONField(default=list)),
                ('secret', models.CharField(max_length=64)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=core.clock.now)),
                ('last_status', models.CharField(blank=True, max_length=60)),
                ('last_delivery_at', models.DateTimeField(blank=True, null=True)),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='webhooks', to='events.event')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='webhooks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
